-- V1 : schéma initial, conforme au modèle de données D2 (docs/diagrammes/D2_datamodel.md).
-- Candidate : Tedjou Nguimzi Cyntia - Matricule 265.

-- ---------------------------------------------------------------------------
-- Données de référence, pré-chargées (H4)
-- ---------------------------------------------------------------------------

CREATE TABLE promotions (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(100) NOT NULL,
    CONSTRAINT uk_promotions_libelle UNIQUE (libelle)
);

CREATE TABLE etudiants (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricule    VARCHAR(20)  NOT NULL,
    nom          VARCHAR(100) NOT NULL,
    prenom       VARCHAR(100) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    promotion_id BIGINT       NOT NULL,
    CONSTRAINT uk_etudiants_matricule UNIQUE (matricule),
    CONSTRAINT uk_etudiants_email UNIQUE (email),
    CONSTRAINT fk_etudiants_promotion FOREIGN KEY (promotion_id) REFERENCES promotions (id)
);

-- ---------------------------------------------------------------------------
-- Sessions de cours
-- ---------------------------------------------------------------------------

CREATE TABLE sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id  BIGINT       NOT NULL,
    titre         VARCHAR(150) NOT NULL,
    code          CHAR(6)      NOT NULL,
    ouverture_at  TIMESTAMPTZ  NOT NULL,
    expiration_at TIMESTAMPTZ  NOT NULL,
    statut        VARCHAR(10)  NOT NULL,
    cloture_at    TIMESTAMPTZ,
    CONSTRAINT uk_sessions_code UNIQUE (code),                                                        -- RG10
    CONSTRAINT ck_sessions_code_format CHECK (code ~ '^[A-Z0-9]{6}$'),                                -- RG10
    CONSTRAINT ck_sessions_expiration CHECK (expiration_at = ouverture_at + INTERVAL '15 minutes'),   -- RG1
    CONSTRAINT ck_sessions_statut CHECK (statut IN ('OUVERTE', 'CLOTUREE')),                          -- RG9
    CONSTRAINT ck_sessions_cloture CHECK ((statut = 'CLOTUREE') = (cloture_at IS NOT NULL)),
    CONSTRAINT fk_sessions_promotion FOREIGN KEY (promotion_id) REFERENCES promotions (id)
);

-- ---------------------------------------------------------------------------
-- Présences
-- ---------------------------------------------------------------------------

CREATE TABLE presences (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT      NOT NULL,
    etudiant_id BIGINT      NOT NULL,
    source      VARCHAR(10) NOT NULL,
    marquee_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_presences_session_etudiant UNIQUE (session_id, etudiant_id),   -- RG3
    CONSTRAINT ck_presences_source CHECK (source IN ('CODE')),                     -- H1
    CONSTRAINT fk_presences_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT fk_presences_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiants (id)
);

-- ---------------------------------------------------------------------------
-- Exercices
-- ---------------------------------------------------------------------------

CREATE TABLE exercices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT        NOT NULL,
    etudiant_id BIGINT        NOT NULL,  -- auteur
    lien        VARCHAR(2048) NOT NULL,
    statut      VARCHAR(20)   NOT NULL,
    depose_at   TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uk_exercices_session_etudiant UNIQUE (session_id, etudiant_id),   -- RG4
    CONSTRAINT ck_exercices_lien CHECK (lien ~* '^https?://'),                     -- RG5 (contrôle complet côté application)
    CONSTRAINT ck_exercices_statut CHECK (statut IN ('DEPOSE', 'EN_RELECTURE', 'RELU', 'DEFINITIF', 'SANS_RELECTURE')),  -- D4
    CONSTRAINT fk_exercices_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT fk_exercices_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiants (id)
);

-- ---------------------------------------------------------------------------
-- Relectures
-- RG2 (relecteur différent de l'auteur) et RG7 (relecteur présent à la session)
-- portent sur plusieurs tables : ils sont contrôlés par l'application.
-- ---------------------------------------------------------------------------

CREATE TABLE relectures (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id  BIGINT      NOT NULL,
    relecteur_id BIGINT      NOT NULL,
    note         SMALLINT,
    commentaire  TEXT,
    statut       VARCHAR(12) NOT NULL,
    attribuee_at TIMESTAMPTZ NOT NULL,
    rendue_at    TIMESTAMPTZ,
    modifiee_at  TIMESTAMPTZ,
    CONSTRAINT uk_relectures_exercice UNIQUE (exercice_id),                                          -- RG8
    CONSTRAINT ck_relectures_note CHECK (note IS NULL OR note BETWEEN 0 AND 20),                     -- RG6
    CONSTRAINT ck_relectures_statut CHECK (statut IN ('EN_ATTENTE', 'RENDUE')),
    CONSTRAINT ck_relectures_rendue CHECK ((statut = 'RENDUE') = (note IS NOT NULL AND rendue_at IS NOT NULL)),  -- EF5
    CONSTRAINT fk_relectures_exercice FOREIGN KEY (exercice_id) REFERENCES exercices (id),
    CONSTRAINT fk_relectures_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiants (id)
);

-- ---------------------------------------------------------------------------
-- Index (D2)
-- presences (session_id) et exercices (session_id) sont couverts par les index
-- des contraintes UNIQUE (session_id, etudiant_id), dont session_id est la
-- première colonne : aucun index supplémentaire n'est nécessaire.
-- ---------------------------------------------------------------------------

CREATE INDEX idx_relectures_relecteur_statut ON relectures (relecteur_id, statut);  -- RG11
CREATE INDEX idx_etudiants_promotion ON etudiants (promotion_id);                   -- tableau
CREATE INDEX idx_sessions_promotion ON sessions (promotion_id);                     -- tableau
